services:
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    image: postgres:16
    container_name: agenda_sync_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - agenda_sync_db:/var/lib/postgresql/data
    networks:
      - agenda_sync_net


  api:
    build:
      context: ./api
    image: agenda_sync_api
    container_name: agenda_sync_api
    environment:
      ASPNETCORE_URLS: "http://+:5069"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      
      Jwt__SecretKey: ${JWT_SECRET}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpiryInMinutes: ${JWT_EXPIRY}

      Google__ClientId: ${GOOGLE_CLIENT_ID}
      Google__ClientSecret: ${GOOGLE_CLIENT_SECRET}
      Google__RedirectUri: "postmessage"
      Google__TokenEndpoint: "https://oauth2.googleapis.com/token"
      Google__CalendarApi: "https://www.googleapis.com/calendar/v3/calendars"

      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}"

      AllowedOrigins__0: "http://localhost:${WEB_PORT}"

    ports:
      - "5069:5069"
    depends_on:
      postgres:
        condition: service_healthy  
    networks:
      - agenda_sync_net

  web_app:
    build:
      context: ./app
    image: agenda_sync_web_app
    container_name: agenda_sync_web_app
    environment:
      VITE_API_URL: "http://localhost:${API_PORT}"
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - api
    networks:
      - agenda_sync_net

networks:
  agenda_sync_net:
    driver: bridge

volumes:
  agenda_sync_db:
